version: '3.8'
services:
  zookeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181 # Where to listen for connections by clients such as Kafka
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181" #localhost:22181 -> container:2181
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeper
    ports:
      - "9092:9092" # localhost:9092 -> container:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeper:2181' # zookeeper service name and port
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT # Define security protocol for listeners
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # Makes Kafka accessible from the outside of the container by advertising an accessible location, which is localhost:9092.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1